# Site wide configuration

title: "Jason Quisberth"
description: "Peronsal page"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
#url: "https://61quisberth.github.io"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Jason Quisberth"
  web: "https://61quisberth.github.io"
  twitter: "jaybaby0000"
  github: "61quisberth"
  bio: "Software Developer from Falls Church, Virginia"
  avatar: "bio-photo.jpg" # 160x160 px image for author byline

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
